const { chromium } = require('playwright');
const fs = require('fs');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||undefined});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://**/*',r=>r.abort());
 await page.addInitScript(()=>{});
 await page.setContent('<html><body></body></html>');
 await page.evaluate(()=>{
  window.savedConfig={ThemeEnabled:true,HeroEnabled:true,PetalsEnabled:true,BuilderHeaderItems:'sakura:flower|header:split|jellyfin:favorites|header:split|jellyfin:user-menu'};
  window.Dashboard={showLoadingMsg(){},hideLoadingMsg(){},alert(){},processPluginConfigurationUpdateResult(){}};
  window.ApiClient={getPluginConfiguration:async()=>({...window.savedConfig}),updatePluginConfiguration:async(id,c)=>{if(window.failSave)throw Error('test failure');window.savedConfig=c},getUrl:p=>p};
  window.events=0;window.addEventListener('sakura-tea:settings-changed',()=>window.events++);
 });
 await page.addScriptTag({content:fs.readFileSync('src/Jellyfin.Plugin.SakuraTea/Inject/Build/sakura-tea-header-core.js','utf8')});
 await page.setContent(fs.readFileSync('src/Jellyfin.Plugin.SakuraTea/Configuration/config.html','utf8'));
 await page.waitForFunction(()=>document.querySelector('#SakuraTeaSaveStatus').textContent==='All changes saved');
 await page.evaluate(()=>window.addEventListener('sakura-tea:settings-changed',()=>window.events++));
 assert.equal(await page.locator('#SakuraTeaSave').isDisabled(),true);
 assert.equal(await page.locator('.st-preview-pill').count(),1);
 assert.equal(await page.locator('[data-item-id="header:split"]').count(),0);
 await page.locator('#BuilderHeroHeight').fill('85');
 assert.equal(await page.locator('#SakuraTeaSave').isEnabled(),true);
 await page.locator('#SakuraTeaDiscard').click();
 assert.equal(await page.locator('#BuilderHeroHeight').inputValue(),'76');
 await page.locator('#SakuraTeaItemSearch').fill('Search');
 assert.equal(await page.locator('#SakuraTeaHeaderAvailable button:visible').count(),1);
 await page.locator('#SakuraTeaHeaderAvailable button:visible').click();
 await page.locator('#SakuraTeaSave').click();
 await page.waitForFunction(()=>window.events===1);
 assert.match(await page.evaluate(()=>window.savedConfig.BuilderHeaderItems),/jellyfin:search/);
 await page.locator('#BuilderHeroHeight').fill('85');
 await page.evaluate(()=>window.failSave=true);
 await page.locator('#SakuraTeaSave').click();
 await page.waitForFunction(()=>document.querySelector('#SakuraTeaSaveStatus').textContent.includes('Could not save'));
 assert.equal(await page.locator('#SakuraTeaSave').isEnabled(),true);
 await page.evaluate(()=>window.failSave=false);
 await page.locator('#SakuraTeaSave').click();
 await page.waitForFunction(()=>window.events===2);
 assert.equal(await page.evaluate(()=>window.savedConfig.BuilderHeroHeight),85);

 await page.locator('button[data-panel="overview"]').click();
 assert.equal(await page.locator('#SakuraTeaSave').isVisible(),true);
 await page.locator('button[data-panel="builder"]').click();
 await page.locator('#SakuraTeaItemSearch').fill('');
 const first=page.locator('.st-preview-item').first();await first.focus();await page.keyboard.press('Delete');
 assert.equal(await page.locator('#SakuraTeaSave').isEnabled(),true);
 // Removing all controls must stay empty after saving and revisiting.
 await page.evaluate(()=>{document.querySelector('#BuilderHeaderItems').value='';document.querySelector('#BuilderHeroHeight').dispatchEvent(new Event('input',{bubbles:true}))});
 await page.locator('#SakuraTeaSave').click();
 await page.waitForFunction(()=>window.events===3);
 assert.equal(await page.evaluate(()=>window.savedConfig.BuilderHeaderItems),'');
 await page.evaluate(()=>document.querySelector('#SakuraTeaConfigPage').dispatchEvent(new Event('pageshow')));
 await page.waitForFunction(()=>!document.querySelector('#SakuraTeaConfigForm').inert);
 assert.equal(await page.locator('.st-preview-item').count(),0);
 await page.locator('#SakuraTeaResetHeader').click();
 await page.locator('#SakuraTeaStyleFields summary').filter({hasText:'Branding'}).click();
 await page.locator('#SakuraTeaStyleFields summary').filter({hasText:'Colours'}).click();
 await page.locator('#BuilderBrandDisplay').selectOption('Both');
 await page.locator('#BuilderHeaderPadding').fill('12');
 await page.locator('#BuilderItemColor').fill('#123456');
 await page.locator('#BuilderLogoX').fill('80');await page.locator('#BuilderNameX').fill('20');await page.locator('#BuilderHeaderY').fill('55');
 assert.equal(await page.locator('.st-preview-brand').count(),2);
 assert.equal(await page.locator('#SakuraTeaHeaderPreview').evaluate(e=>e.style.getPropertyValue('--st-bar-padding')),'12px');
 await page.locator('#SakuraTeaSave').click();await page.waitForFunction(()=>window.events===4);
 assert.equal(await page.evaluate(()=>window.savedConfig.BuilderItemColor),'#123456');
 assert.equal(await page.evaluate(()=>window.savedConfig.BuilderLogoX),80);assert.equal(await page.evaluate(()=>window.savedConfig.BuilderHeaderY),55);
 await page.locator('#BuilderBrandDisplay').selectOption('None');await page.locator('#SakuraTeaDiscard').click();
 assert.equal(await page.locator('#BuilderBrandDisplay').inputValue(),'Both');
 await page.locator('button[data-panel="overview"]').click();await page.locator('#HeaderEnabled').uncheck();await page.locator('#DetailsEnabled').check();
 await page.locator('#SakuraTeaSave').click();await page.waitForFunction(()=>window.events===5);
 assert.equal(await page.evaluate(()=>window.savedConfig.HeaderEnabled),false);assert.equal(await page.evaluate(()=>window.savedConfig.DetailsEnabled),true);
 await page.locator('button[data-panel="builder"]').click();
 await page.screenshot({path:'/tmp/sakura-builder-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.locator('button[data-device="mobile"]').click();
 await page.screenshot({path:'/tmp/sakura-builder-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS: load, dirty tracking, discard, search, add, save, failure/retry, overview Save, keyboard remove, desktop/mobile render');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
