const {chromium}=require('playwright');const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||undefined});try{
 const page=await browser.newPage({viewport:{width:1200,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setContent('<style>body{margin:0;background:#100e14;color:#fff;font:16px system-ui}.detailPageWrapperContainer{padding:20px}.hide{display:none!important}</style><main id="itemDetailPage"><div id="itemBackdrop"></div><div class="detailPageWrapperContainer"><div class="detailPagePrimaryContainer"><div class="nameContainer"><h1>Featured anime</h1></div><p class="overview">A cinematic detail page keeps your native playback controls.</p><div class="mainDetailButtons"><button class="btnPlay">Resume</button><button class="btnDownload hide">Download</button><button class="btnUserRating">Favourite</button></div></div><section class="detailPageSecondaryContainer"><h2 class="sectionTitle">Episodes</h2><button>Episode 1</button></section></div></main>');
 await page.evaluate(()=>{location.hash='#/details?id=one';window.enabled=true;window.itemType='Series';window.count=0;window.ApiClient={getCurrentUserId:()=> 'viewer',serverId:()=> 'server',getUrl:p=>p,ajax:async()=>({DetailsEnabled:window.enabled}),getItem:async()=>{if(window.hold)await new Promise(resolve=>window.release=resolve);return {Id:'one',Name:'Featured anime',Type:window.itemType,CommunityRating:8.5,ProductionYear:2026,Genres:['Animation']}}};window.original=document.querySelector('.mainDetailButtons');window.original.querySelector('.btnPlay').onclick=()=>window.count++});
 await page.addStyleTag({content:fs.readFileSync('src/Jellyfin.Plugin.SakuraTea/Inject/Theme/sakura-tea-details.css','utf8')});
 await page.addScriptTag({content:fs.readFileSync('src/Jellyfin.Plugin.SakuraTea/Inject/Build/sakura-tea-details.js','utf8')});
 await page.locator('.sakuraTeaDetailHero').waitFor();assert.equal(await page.evaluate(()=>document.querySelector('.sakuraTeaDetailHero .mainDetailButtons')===window.original),true);
 await page.getByRole('button',{name:'Resume',exact:true}).click();assert.equal(await page.evaluate(()=>window.count),1);assert.equal(await page.locator('.btnDownload').isVisible(),false);
 assert.equal(await page.getByRole('button',{name:'Episode 1',exact:true}).isVisible(),true);
 await page.screenshot({path:'/tmp/sakura-detail-upgrade.png'});
 await page.evaluate(()=>{document.documentElement.classList.add('sakura-tea-dark');window.dispatchEvent(new Event('sakura-tea:appearance-changed'))});
 await page.locator('.sakuraTeaDetailHero').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>document.querySelector('.detailPagePrimaryContainer .mainDetailButtons')===window.original),true);
 await page.evaluate(()=>{document.documentElement.classList.remove('sakura-tea-dark');window.dispatchEvent(new Event('sakura-tea:appearance-changed'))});await page.locator('.sakuraTeaDetailHero').waitFor();
 await page.evaluate(()=>{window.enabled=false;window.dispatchEvent(new Event('sakura-tea:settings-changed'))});await page.locator('.sakuraTeaDetailHero').waitFor({state:'detached'});
 await page.evaluate(()=>{window.enabled=true;window.hold=true;window.dispatchEvent(new Event('sakura-tea:settings-changed'))});await page.waitForFunction(()=>Boolean(window.release));
 await page.evaluate(()=>{location.hash='#/home'});await page.waitForTimeout(150);await page.evaluate(()=>{window.hold=false;window.release()});await page.waitForTimeout(150);assert.equal(await page.locator('.sakuraTeaDetailHero').count(),0);
 for(const type of ['Movie','Season','Episode']){await page.evaluate(type=>{window.itemType=type;location.hash='#/details?id='+type;document.dispatchEvent(new Event('viewshow'))},type);await page.locator('.sakuraTeaDetailHero').waitFor();}
 await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),360);await page.screenshot({path:'/tmp/sakura-detail-upgrade-mobile.png'});
 await page.evaluate(()=>{location.hash='#/details?id=unsupported';window.itemType='MusicAlbum'});await page.locator('.sakuraTeaDetailHero').waitFor({state:'detached'});
 assert.deepEqual(errors,[]);console.log('PASS: native nodes and playback preserved, hidden downloads stay hidden, dark/disabled/route restoration, late responses, four media types, mobile fallback');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
